### ISSUE TITLE
NEWS update for 8.0.2

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#100]
[New text below -- note I haven't reproduced links here. Changes from current dev version in bold.]

Revolution R Open 8.0.2 is beta-test software. It has been tested and we expect it to work on all supported platforms, but will retain the "beta" label while we gather feedback from the community. Please report any problems or suggestions to the RRO Google Group.

**Revolution R Open 8.0.2 is based on R 3.1.2.**

Supported platforms include:
* Ubuntu 12.04, 14.04
* CentOS / Red Hat Enterprise Linux 5.8, 6.5, 7.0
* Mac OS X Mavericks (10.9) & Yosemite (10.10)
* Windows® 7.0 SP1, 8.0, 8.1, Windows Server® 2008 R2 SP1 and 2012
* **Experimental platform: OpenSUSE 13.1. RRO has not been fully tested on experimental platforms, but we expect it to work.** Please report any issues to the RRO Google Group.

The default CRAN mirror has been updated to point to the fixed CRAN repository snapshot from March 1, 2015. Visit our Spotlight page to read more about some of the new and updated packages available using that snapshot date as the default repository for this release.

**The MKL accelerated math library is now an optional download for Windows and Linux systems. After installing RRO, download the "Math Library" installer and install it to enable multi-threaded math on these platforms.**

**Comment by j-martens** [comment]
Also, addressed in this commit: 1f96495f83125784e93fb95e454291694e5e3be7
