### ISSUE TITLE
Add release notes to tagged release for 8.0.2

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#102]
As part of the release process, we include release notes when we are taking our release. We should have the release notes and known issues ready to paste into the page.

https://github.com/RevolutionAnalytics/RRO/releases

**Comment by j-martens** [comment]
Here is one known defect to include:

The RRO GUI (RRO.app) on OS X fails whenever you attempt to load a package that launches a tcltk window (for example, the HH package). To work around this issue, use R in a terminal window or another IDE such as RStudio for these packages. [Issue #107]

**Comment by andrie** [comment]
The draft release notes are at

https://docs.google.com/a/revolution-computing.com/document/d/1YVY5LI8kTy598Fp_TlVb1IlMVXedds6lzhL0HJ9xLZQ/edit#
