### ISSUE TITLE
RRO 8.0.2 on Mac OSX problem with HH package

### ISSUE THREAD

**Issue by sdgilley** [RevolutionAnalytics/RRO#107]
After installing RRO 8.0.2, the following code works successfully in RStudio:

install.packages('HH')
library(HH)

However, in the RRO GUI, the following occurs in the console window:
> library(HH)
Loading required package: lattice
Loading required package: grid
Loading required package: latticeExtra
Loading required package: RColorBrewer
Loading required package: multcomp
Loading required package: mvtnorm
Loading required package: survival
Loading required package: splines
Loading required package: TH.data
Loading required package: gridExtra
2015-03-11 16:49:03.466 Revolution R Open[58190:2262156] -[NSApplication _setup:]: unrecognized selector sent to instance 0x608000109000
2015-03-11 16:49:03.467 Revolution R Open[58190:2262156] *** run_REngineRmainloop: exception -[NSApplication _setup:]: unrecognized selector sent to instance 0x608000109000 caught during REPL iteration. Update to the latest GUI version and consider reporting this properly (see FAQ) if it persists and is not known.
Consider saving your work soon in case this develops into a problem.
> 

---
In RSTudio, a dialog box appears during the process, I suspect that is where the error occurs in the RRO GUI.

**Comment by sfweller** [comment]
Hi Sherri,

This works for me trying this in the latest 8.0.3 Beta for RRO on Windows - what version of RRO does this fail in?

**Comment by sfweller** [comment]
What is the platform and version of OS?

**Comment by sdgilley** [comment]
See bug title - RRO 8.0.2 on Mac.  The problem also seems to exist in Mac OSX 8.0.1, as this was first reported on the Google Group for 8.0.1(Mac).  At first I didn't think we could reproduce, because I was running in RStudio.  Then I tried it on the RRO GUI and could reproduce (on 8.0.2).  While I didn't try it on 8.0.1, as I said, that's where the report first came from.

**Comment by sdgilley** [comment]
Further info: from my RRO GUI (where this package fails)
> capabilities()
    jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets 
    TRUE     TRUE     TRUE     TRUE    FALSE     TRUE     TRUE     TRUE 
  libxml     fifo   cledit    iconv      NLS  profmem    cairo      ICU 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found
>

**Comment by sdgilley** [comment]
I've now uninstalled RRO and installed CRAN R 3.1.2.  It also fails BUT it gives a much different error message:
> library(HH)
Loading required package: lattice
Loading required package: grid
Loading required package: latticeExtra
Loading required package: RColorBrewer
Loading required package: multcomp
Loading required package: mvtnorm
Loading required package: survival
Loading required package: splines
Loading required package: TH.data
Loading required package: gridExtra
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
In addition: Warning message:
package ‘multcomp’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘HH’
>

**Comment by revodavid** [comment]
I was able to install and load the HH library successfully from the terminal today. `install.packages("HH")` successfully installed HH and several dependencies. Then when I ran `library(HH)` the following dialogs appeared:

![screen shot 2015-03-26 at 9 56 29 am](https://cloud.githubusercontent.com/assets/152948/6849106/0016a040-d39f-11e4-8a90-64fa42ffeb5c.png)

I clicked Yes.

![screen shot 2015-03-26 at 9 56 42 am](https://cloud.githubusercontent.com/assets/152948/6849108/069a0650-d39f-11e4-8aeb-f4741b4021b4.png)

I clicked OK. Then several more packages were installed, and eventually the R prompt appeared without further errors and just this warning:

```
The downloaded binary packages are in
	/var/folders/hy/wcdcll0j0m3bf0_c14dgm3zh0000gn/T//RtmpQvGn6H/downloaded_packages
Warning message:
package ‘multcomp’ was built under R version 3.1.3 
>
```

**Comment by revodavid** [comment]
However, calling `library(HH)` from Revolution R Open.app yields the following:

```
> library(HH)
Loading required package: lattice
Loading required package: grid
Loading required package: latticeExtra
Loading required package: RColorBrewer
Loading required package: multcomp
Loading required package: mvtnorm
Loading required package: survival
Loading required package: splines
Loading required package: TH.data
Loading required package: gridExtra
2015-03-26 10:03:06.200 Revolution R Open[18455:8101742] -[NSApplication _setup:]: unrecognized selector sent to instance 0x60800010a170
2015-03-26 10:03:06.201 Revolution R Open[18455:8101742] *** run_REngineRmainloop: exception -[NSApplication _setup:]: unrecognized selector sent to instance 0x60800010a170 caught during REPL iteration. Update to the latest GUI version and consider reporting this properly (see FAQ) if it persists and is not known.
Consider saving your work soon in case this develops into a problem.
```

**Comment by sfweller** [comment]
Confirmed as working in RRO 8.0.3 on Mac OS-X Yosemite 10.10.1.

**Comment by revodavid** [comment]
In that case we should remove it from the release notes for 8.0.3.
