### ISSUE TITLE
Bad character in 8.0.1 Beta 2 release notes

### ISSUE THREAD

**Issue by taylorterry3** [RevolutionAnalytics/RRO#110]
This is extremely minor, but it confused the hell out of me for about 5 minutes so I figured I'd report it. In @revodavid's release notes at https://github.com/RevolutionAnalytics/RRO/releases/tag/v8.0.1-beta2 there is a one liner near the bottom that creates a symlink for the BLAS library. Between `sudo` and `ln` are a space and then some weird junk characters that cause the command to fail when pasted to the terminal. See below; symlink.txt is just a paste of the command as copied from the web.

```
$ cut -c 1-9 symlink.txt | od -ca
0000000    s   u   d   o          **  **   l   n      \n                
           s   u   d   o  sp   ?  80   ?   l   n  sp  nl                
0000014
```

Thanks for providing RRO, it's an awesome project!

**Comment by j-martens** [comment]
Thank you @taylorterry3 for reporting this. I believe it is fixed now.
