### ISSUE TITLE
accounting for packages removed from CRAN

### ISSUE THREAD

**Issue by sdgilley** [RevolutionAnalytics/RRO#114]
When a package is removed from CRAN, we correctly no longer show it in the packages table.  However, we may still display information about the package if the user types the URL for it, such as 
http://mran.revolutionanalytics.com/packages/info/?tRakt . 

The links on this page for the manual, vignette, and source won't work because the package was removed from CRAN.

**Comment by revodavid** [comment]
This should be an MRAN issue, not an RRO issue.
