### ISSUE TITLE
Ubuntu 15.04 support

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#118]
Once complete Ubuntu 12.04, 14.04 and 15.04 are supported versions.

(We are skipping 14.10, as it's not a long-term support version. Our general policy will be to support the most-recent Ubuntu version plus the last two LTS versions.)

**Comment by j-martens** [comment]
When you are done, please assign to me Nick.

**Comment by nriesland** [comment]
15.04 has been added to the Jenkins build

**Comment by revodavid** [comment]
Support included in 8.0.3
