### ISSUE TITLE
Crash in RStudio running RRO on Windows with MKL installed

### ISSUE THREAD

**Issue by sfweller** [RevolutionAnalytics/RRO#119]
When you attempt to load the RevoUtilsMath library with:
>library(RevoUtilsMath)

you get an 'R Session Aborted' dialog: R encountered a fatal error - the session was terminated'.
Problem does not happen when running  Rgui.exe with RRO or when loading RevoUtilsMath package in Revolution R Enterprise.

Issue reported by a user running Windows 8.1, but problem also occurs on Windows system running Windows 7 and Rstudio desktop.

**Comment by revodavid** [comment]
Any call to BLAS or LAPACK crashes the R session, even without loading the RevoUtilsMath package. Something as simple as:

```
x<-rnorm(10)
y<-rnorm(10)
m<-lm(x~y)
```

works in RGui or R cmd lline, but crashes in RStudio

**Comment by andrie** [comment]
David Champagne tested and resolved

**Comment by sfweller** [comment]
Works with latest RRO installer and latest RevoMath installer for 8.0.3.
