### ISSUE TITLE
8.0.3 - Update readme.txt and readme.md

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#121]
For the release, update these files. Look for the version numbers, beta versions, and repository dates. Also, ask DS for legal review.

**Comment by j-martens** [comment]
The readme.md and readme.txt currently reference:

RRO version number: 8.0.3
R version number: 3.1.3
Repos date: April 1, 2015

A legal review may still be needed by @revodavid

**Comment by revodavid** [comment]
No changes required for readme.txt
Readme.md need to update R version numbers (see PR)

**Comment by j-martens** [comment]
Cannot reproduce the R version issue on the dev branch.
