### ISSUE TITLE
8.0.3 - Write github release notes and put in pre-release

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#122]
Work with AdV and DS to finalize release notes for github.
Save as pre-release in anticipation of final release.

**Comment by j-martens** [comment]
DRAFT DRAFT DRAFT

This release of Revolution R Open fixes some bugs, and uses the R engine 3.1.3. We recommend upgrading to this version if you are experiencing any of the issues listed in the “Fixed bugs” section.

## Highlights
+ Based on R-3.1.3

## Fixed bugs


## Known issues


## Download the binaries
Visit [http://mran.revolutionanalytics.com/download/](http://mran.revolutionanalytics.com/download/) to download the binary distribution.

**Comment by swells** [comment]
This looks correct.

**Comment by andrie** [comment]
First rough draft ready (in original issue description).  Outstanding item: review bug fixes and improvements and include in notes.

Pinging @j-martens and @revodavid

**Comment by andrie** [comment]
Add note on RevoMath uninstall

**Comment by andrie** [comment]
This is now drafted as a pre-release at https://github.com/RevolutionAnalytics/RRO/releases
