### ISSUE TITLE
8.0.3 - Update the customer (download) letter

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#123]
Verify that we are still doing it this way with Yonnie. Make any updates to the content.

**Comment by j-martens** [comment]
The current letter maintained by Yonnie is for the RRP program. 
Is there a replacement for this customer letter, @revodavid? Should we remove this task from the release checklist for now?

**Comment by revodavid** [comment]
This should remain part of the release checklist, but it's not a task for this project.
