### ISSUE TITLE
MKL install script bad path to RevoUtilsMath.tar.gz in some case

### ISSUE THREAD

**Issue by grumpycatt** [RevolutionAnalytics/RRO#128]
If you run the install script outside of RevoMath directory, you won't be able to install correctly the R package RevoUtilsMath.tar.gz. This is due to this line of code into the shell script :

- $R_PATH CMD INSTALL RevoUtilsMath.tar.gz  > mkl_log.txt 2>&1

In order to fix it, I just added the PWDD before the package call :

- $R_PATH CMD INSTALL $PWDD/RevoUtilsMath.tar.gz  > mkl_log.txt 2>&1

Hope it helps,

Regards

**Comment by sfweller** [comment]
Confirmed that fix has been added to RevoMath.sh in RRO 8.0.3 RC.
