### ISSUE TITLE
Check at session start if checkpoint installed correctly

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/RRO#130]
The installation of `checkpoint` from MRAN can fail, for example when installation happens without an internet connection.

Currently, there is no warning if `checkpoint` fails to install.  This is a bug, since the promise of RRO is that `checkpoint` is part of the system (for reproducibility).

Possible option:

* Add a test in `Rprofile` to confirm if `checkpoint` is available (potentially also the version number).  If not installed, install from MRAN, potentially after confirming with the user (in interactive mode)

https://github.com/RA-Internal/MRAN-site/issues/220

**Comment by sfweller** [comment]
Maybe we could add a R test to see if a user has a valid current internet connection?

Here are some suggestions I found for that in this writeup on stackoverflow:
http://stackoverflow.com/questions/5076593/how-to-determine-if-you-have-an-internet-connection-in-r

**Comment by andrie** [comment]
@sfweller Nice suggestion. This would be an improvement on the following raw installation checking code:

```r
if(!"checkpoint" %in% installed.packages()[, "Package"]){
  message("Installing missing checkpoint package")
  install.packages("checkpoint", repos = "http://mran.revolutionanalytics.com/snapshot/2015-04-29")
}

```

**Comment by j-martens** [comment]
@sfweller recommened we could have an automated test for this.

Backlogged to see if checkpoint gets bundled.

**Comment by j-martens** [comment]
Related to https://github.com/RA-Internal/MRAN-site/issues/220
