### ISSUE TITLE
Install checkpoint from 2015-04-29 MRAN snapshot

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/RRO#131]
The windows binary for `checkpoint-0.3.10` was captured in the 2015-04-29 snapshot.

Use

```r
install.packages("checkpoint", repos = "http://mran.revolutionanalytics.com/snapshot/2015-04-29")
```

to install

**Comment by andrie** [comment]
I downloaded RRO from devstaging this morning and I get `checkpoint` version 0.3.9 instead of 0.3.10.

Could this be linked to an installation date that is incorrect?

**Comment by andrie** [comment]
The code in the [dev branch](https://github.com/RevolutionAnalytics/RRO/commit/90b50a109044c576c82a39bfa2b3676f50234cdd)  looks ok.

Did I download the correct installer?

**Comment by andrie** [comment]
Additional information: It seems that `RRO-8.0.3 build 24` does not install `checkpoint` **at all** on Windows.

On a clean machine, new install, `checkpoint` is not in the user library nor the system library.

**Comment by revodavid** [comment]
I also find I have checkpoint 0.3.9 installed in my Windows install. I
didn't do a full uninstall, so it's possible it's from an older
installation.

# David

-- 
David M Smith <davidsmi@microsoft.com>
Chief Community Officer, Revolution Analytics
http://blog.revolutionanalytics.com
Revolution Analytics is a wholly-owned subsidiary of Microsoft.
Tel: +1 (650) 646-9523 (Chicago IL, USA)
Twitter: @revodavid

**Comment by revodavid** [comment]
Looking closer, I see that .libPaths() is

```
[1] "C:/Users/davidsmi/Documents/R/win-library/3.1"
[2] "C:/Program Files/RRO/R-3.1.3/library" 
```

`checkpoint` is installed in `C:/Users/davidsmi/Documents/R/win-library/3.1` and not in `C:/Program Files/RRO/R-3.1.3/library`.
