### ISSUE TITLE
Side-by-side installs on Windows not possible when using MKL

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#133]
If you try and install MKL when it's already installed, you get this message:
"Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel."

**Comment by revodavid** [comment]
Uninstalling "RevoMath" from Add/Remove programs allows you to run the installer. It's not clear from the error message that "RevoMath" is the thing you need to uninstall, though.

**Comment by j-martens** [comment]
Is this something we want to document in the uninstall instructions or  update in the software messages?

**Comment by andrie** [comment]
I think we should.

Specifically, this only happens with RRO-8.0.2 and RevoUtils.

In RRO-8.0.3 the RevoUtils download has a matching version number, thus allowing future side-by-side installs.

**Comment by j-martens** [comment]
We need to ensure that we can do side by side installs of Windows RRO with MKL 8.0.3 and 3.2.0.

@revodavid  @nathansoz

**Comment by j-martens** [comment]
@sdgilley reports that the 3.2.0 build she just tested works side by side with 8.0.3.

**Comment by revodavid** [comment]
See also #135 -- is this also fixed now?

**Comment by j-martens** [comment]
Note added states: 

Warning! If you are attempting to reinstall the MKL math library for Revolution R Open 3.2.0, then you must first uninstall RevoMath from within the Add or Remove Programs or Uninstall a program dialog before proceeding with the reinstall.

**Comment by j-martens** [comment]
Uninstall/reinstall warning to be added to package by RCalaway.
