### ISSUE TITLE
library(RevoUtilsMath) generates an error dialog if MKL not loaded

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#135]
On Windows, if you install RRO but do *not* install MKL, then `library(RevoUtilsMath)` pops up an error dialog with the message "The procedure mkl_get_max_threads could not be found"

(This occured when I reinstalled RRO 8.0.3 over an existing install but didn't reinstall MKL.)

Instead, provide an error message in the R console: "To use RevoUtilsMath you must first install the MKL Math Library. Visit http://mran.revolutionanalytics.com/download ."

**Comment by j-martens** [comment]
This is being address by a warning message in the package stating that you must first uninstall MKL and then reinstall it. #133
