### ISSUE TITLE
wrong version of RevoMath in 5/18 build

### ISSUE THREAD

**Issue by sdgilley** [RevolutionAnalytics/RRO#139]
The RevoMath installer for Windows is in a file called RevoMath-3.2.0.  However, when I launch this the screen is labeled RevoMath-8.0.3 Setup.  I spoke with Nathan who indicated he had not yet built the 3.2.0 version of RevoMath; thus this is indeed still the old version.  We need the 3.2.0 version to ship with RRO 3.2.0.

**Comment by j-martens** [comment]
It appears as 8.0.3 now. Ready for QA.

**Comment by andrie** [comment]
downloaded from http://devstaging.mran.io/download/#download and tried on Windows.

Although the installer says RevoMath-3.2.0, internally it refers to RRO-8.0.3 so doesn't link correctly.

There still is something wrong, AFAICT

**Comment by revodavid** [comment]
Still an issue for me after downloading 10 mins ago.

![image](https://cloud.githubusercontent.com/assets/152948/7713743/40ca3a82-fe3f-11e4-8cee-095cc0e13518.png)

**Comment by revodavid** [comment]
This breaks the installation process -- it does not install when you click next, instead you get options to Repair or Remove.

**Comment by nathansoz** [comment]
In talking with @j-martens and @nriesland it appears that the Devstaging site was never updated with the most recent MKL installer. This should be fixed now.

**Comment by j-martens** [comment]
It appears that a Jenkins copy job went awry. The set up screen now shows 3.2.0 on my Win machine.

**Comment by revodavid** [comment]
I have the new build but it skips the entire "Welcome to the RevoMath" page. The first thing you see is "Please read the RevoMath-3.2.0 License Agreement"

**Comment by j-martens** [comment]
The welcome screen appears for 3.2.0 (and 8.0.3) **ONLY** when you attempt to install over an existing MKL of the same version. This welcome screen has a notice similar to the following:
"Setup allows you to change the way RevoMath features are installed on your computer or to remove it from your computer. Click Next to continue."

If you'd like to add a welcome screen to fresh installs, we can add a card for a future release. Please let me know.

**Comment by revodavid** [comment]
There should be a welcome screen -- please add a card.

**Comment by j-martens** [comment]
Card added here: https://github.com/RevolutionAnalytics/RRO/issues/145

This issue is now resolved.

**Comment by sfweller** [comment]
Verified that this has been fixed in latest devstaging build.
