### ISSUE TITLE
wrong checkpoint date noted in text at startup

### ISSUE THREAD

**Issue by sdgilley** [RevolutionAnalytics/RRO#140]
When starting RRO 3.2.0, the text at the top says:
Using CRAN snapshot taken on 2015-04-01

This is not the correct date.  In fact, getOption shows the correct date:
> getOption("repos")
                                                     CRAN 
"http://mran.revolutionanalytics.com/snapshot/2015-05-01" 

The text needs to be updated to use this date as well.

**Comment by nriesland** [comment]
text has been updated to 2015-5-01
