### ISSUE TITLE
R 3.2.1 engine 

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#141]
To be released on June 18. First prerelease on June 8

**Comment by nathansoz** [comment]
#171 pulls the beta sources. We still will need to pull release source when they are available.

**Comment by j-martens** [comment]
As #171 states: when R goes live we can simply swap the R-src directory, leaving everything else the same.

**Comment by j-martens** [comment]
Check all platforms please.

**Comment by j-martens** [comment]
Tracking in testing spreadsheet with @richcalaway
