### ISSUE TITLE
MKL installer needs Welcome Screen

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#145]
Currently, there is no Welcome Screen on a fresh installation of MKL.  We should add one that looks similar to the Welcome that appears when you attempt to reinstall over MKL.

If we have control over the text in that screen, here is the suggested text to use:

Welcome to the RevoMath-3.2.1 Setup Wizard

This setup wizard allows you to install the RevoMath library on your computer. Click Next to continue or Cancel to exit the Setup Wizard."

**Comment by nathansoz** [comment]
Upgrading my estimate on this. I spent about an hour on this today and its a bit more complicated than meets the eye.

**Comment by nathansoz** [comment]
Fixed in SVN/ParallelR/14836
