### ISSUE TITLE
MKL on Ubuntu looking for RRO under different directory

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#151]
Issue reported by user on googlegroup below:

-------------
Hello,

I installed RRO-3.2 on Ubuntu 15.04 64-bit, and then attempted to install the matching MKL library. Looks like the installation script wasn't able to find RRO-3.2 installed, and therefore refused to install MKL. At least in my system, I was able to trace it down to an error in the expected RRO installation path, lines 89 and 95 of RevoMath.sh

My RRO installation folder: /usr/lib64/RRO-3.2.0/R-3.2.0/lib/R/bin/R
The RRO installation folder expected from the script: /usr/lib64/RRO-3.2.0/R-3.2.0/lib64/R/bin/R

Best,

Roberto
-- 
To view this discussion on the web visit https://groups.google.com/d/msgid/rropen/a45e6d61-4b25-41e8-8175-36276cea7f4c%40googlegroups.com.

**Comment by j-martens** [comment]
#152 is a duplicate.

**Comment by j-martens** [comment]
@sfweller to see why it is installing to `lib` instead of `lib64` and let @nathansoz know.

**Comment by sfweller** [comment]
I see what the customer is getting at, but I was not able to reproduce the error or problem they were seeing when trying a fresh install on a Ubuntu 1504 system.  The MKL installer worked correctly as far as I can tell and I verified that it copied the mkl files to the directory:
/usr/lib64/RRO-3.2.0/R-3.2.0/lib/R/lib
The benchmark tests also ran successfully, after the install. 

The RRO installation folder on Ubuntu is different '/usr/lib64/RRO-3.2.0/R-3.2.0/lib' than the target folder that is set in line 85 of the RevoMath.sh script. That appears to be what the customer is referring to above. Is that something that needs to be fixed Nathan?  Should this bug be reassigned to Nick to look at that?

**Comment by j-martens** [comment]
Rich will be trying to reproduce.

**Comment by j-martens** [comment]
@richcalaway not able to reproduce.

**Comment by j-martens** [comment]
Unreproducible.
