### ISSUE TITLE
MKL Windows install doesn't work if CRAN R 3.2.0 is installed side by side

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#152]
Reported by Paolo on Windows 7 64-bit:

After installing RRO 3.2.0 and the MKL Math Libraries I tried to load the library RevoUtilsMath but RRO returned the error message saying the library didn't exist.

I found the library being installed in the wrong path (under the usual R3.2.0 rather than the correct RRO/R3.2.0) by the MKL Math Libraries installer.
After moving the library I tried again to load it but I got the following error message:

> library(RevoUtilsMath)
Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: fun(libname, pkgname)
  error: To use RevoUtilsMath you must first install the MKL Math Library.
 Visit http://mran.revolutionanalytics.com/download.
 If you have previously installed the MKL Math Library,
remove it using Add/Remove Programs, then re-install.
Error: package or namespace load failed for ‘RevoUtilsMath’

**Comment by j-martens** [comment]
I responded with:
Hi Paolo, 

This issue is due to the fact that for most R users, including yourself, the default library path points to your user folder instead of RRO. The MKL installer was expecting it to point to RRO. 

To get MKL working on your system:

1. Please remove the file you copied and uninstall MKL. This way we'll start with a clean slate.

2. Reset the library path for the current session, type:
    .libPaths("C:/Program Files/RRO/R-3.2.0/library")  

(Tip: To make this change permanently you'd have to put this in your C:/Program Files/R-3.2.0/etc/Rprofile.site)

3. Install MKL again.

Let me know if that fixes the issue for you.

Josée

**Comment by j-martens** [comment]
Shouldn't the MKL Installer handle this so that it either prompts for the user lib path or makes it RRO?

**Comment by j-martens** [comment]
It appears to be an issue on Ubuntu as well: https://groups.google.com/forum/#!topic/rropen/0jilphZF7E4

**Comment by j-martens** [comment]
The RRO 3.2.0 installer uses the same registry key as R 3.2.0. This may be the issue. A unique key should solve this.

**Comment by guanhuac** [comment]
Encounter same problem of MRO, first install MRO, and then MKL, MKL does not work. Then I uninstalled the preexisting R 3.1.3, uninstall MRO, uninstall MKL, restart the computer; then reinstall MRO, MKL; MKL still can not be loaded!!

**Comment by sfweller** [comment]
Hi guanhuac,

Can you please try the following to work around the problem:

1) . Please remove the file you copied and uninstall MKL. This way we'll start with a clean slate.

2).   Reset the library path for the current session, type:
      .libPaths("C:/Program Files/Microsoft/MRO/R-3.2.3/library") 

(Tip: To make this change permanently you'd have to put this in your C:/Program Files/Microsoft/MRO/R-3.2.3/etc/Rprofile.site)

Then install MKL again.

Let me know if this works for you.


Stephen Weller
Microsoft R Open Technical Support

**Comment by guanhuac** [comment]
No, it make thing worse. When I add to the Rpfofile.site and then install MKL again. The R/MRO fail to open with error message "The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem".

**Comment by sfweller** [comment]
What version of Windows are you running on?  The 'MSVCR120.dll' error can probably be fixed by installing an updated Visual C++ Redistributable library, but it would be good to get that information first.

Stephen Weller
Microsoft R Open Technical Support

**Comment by guanhuac** [comment]
I am using Windows 10.

**Comment by ziyadsaeed** [comment]
where in Rprofile.site should i change the library path?

**Comment by ziyadsaeed** [comment]
inside my Rprofile.site file I added this
.libPaths(c("C:/Users/---/Documents/R/win-library/3.2", "C:/Program Files/Microsoft/MRO/R-3.2.3/library"))

replace --- with user name

**Comment by sfweller** [comment]
Yes, I think that may be the solution. guanhuac, can you please try this suggestion and confirm whether MKL still works in this case:

inside my Rprofile.site file I added this
 .libPaths(c("C:/Users/---/Documents/R/win-library/3.2", "C:/Program Files/Microsoft/MRO/R-3.2.3/library"))

replace --- with user name


Stephen Weller

**Comment by StevenDuttRoss** [comment]
I have the same problem. Even with this path .libPaths(c("C:/Users/---/Documents/R/win-library/3.2", "C:/Program Files/Microsoft/MRO/R-3.2.3/library")) , my microsoft R is not working and the RStudio stop working.

**Comment by lixzhang** [comment]
I had the same problem. Solved it by uninstalling MRO and RevoMath from control panel, then deleting the MRO folder on C drive (C:\Program Files\Microsoft\MRO), and finally installing MRO followed by RevoMath.

**Comment by StevenDuttRoss** [comment]
After launching Rgui.exe there was an error message telling '... msvcr120.dll is missing'.  I already try uninstall RevoMath. We I uninstall, the MRO and the RStudio can work. But when I install the  RevoMath the MRO and the RStudio stop working.
Appreciate any comments!
Thanks!

**Comment by mekkim** [comment]
Since the crash issue I reported also
      involves the Microsoft Visual C Runtime (although the error I got
      was the generic system-access-only msvcrt.dll, not msvcr120.dll
      which is probably from Visual Studio 12), these two issues might
      be related.
      
      Thought I would mention it in case it helps with troubleshooting. 
      The issue might be in the toolchain used for compiling MRO (or
      options used) and hence not visible in the source (I spent a LOT
      of time digging through the MRO source and coudn't find any
      mention of any VC runtimes...  The R Base documentation says that
      it uses malloc.c instead anyways, so that could be why base R has
      no issues.)
      
      Mekki
      
      On 2016-01-30 2:39 PM, Steven Ross wrote:
    
    
      After launching Rgui.exe there was an error message telling
        '... msvcr120.dll is missing'. I already try uninstall RevoMath.
        We I uninstall, the MRO and the RStudio can work. But when I
        install the RevoMath the MRO and the RStudio stop working.
        Appreciate any comments!
        Thanks!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by krz** [comment]
I get the exact same install error in Ubuntu 15.
Might be because I wasn't aware of a running CRAN R process during installation.
I did remove mro (apt-get remove mro) and tried to uninstall MKL through the script which never worked.
I uninstalled CRAN R, installed MRO again, but installing MKL again produces this error.

**Comment by sfweller** [comment]
Hello krz,

You don't mention what the error is you are getting - can you be a bit more specific?

Thanks.

Stephen Weller
Microsoft R Open Technical Support

**Comment by sfweller** [comment]
We will have a MRO patch available that should fix the msvcrt120.dll problem. I will let everyone know once it is available for download.


Stephen Weller
Microsoft R Open Technical Support

**Comment by krz** [comment]
I was getting the same error as in the original post. However, I was able to fix it now by uninstalling all CRAN packages (apt-get remove r-cran*) and deleting the MRO directory in /usr/lib64

**Comment by skanskan** [comment]
The only solution I found it works is:
Move your ...  \R-3.2.3\library  to a save place
uninstall Revomath
uninstall R
install a new R
install Revomath
move your original library folder inside, but don't overwrite anything.

That way you won't need to reinstall all the packages.
