### ISSUE TITLE
3.2.1 Update Readmes

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#153]
Update and review legal info in readme.txt and readme.md for RRO

**Comment by j-martens** [comment]
Still needed:
+ Update this email address in the Readme.txt:  " comments and suggestions to the
Revolution R Open team at Revolution Analytics by emailing
open@revolutionanalytics.com."

+ https://github.com/RevolutionAnalytics/RRO/blob/dev/README.md Needs to be updated with new build information for SLES

**Comment by j-martens** [comment]
@revodavid - is this still the right email address and info? 
Revolution R Open team at Revolution Analytics by emailing
open@revolutionanalytics.com."

**Comment by revodavid** [comment]
That email address still stands, for now.

From: j-martens
Reply-To: RevolutionAnalytics/RRO
Date: Thursday, July 2, 2015 at 2:50 AM
To: RevolutionAnalytics/RRO
Cc: David Smith
Subject: Re: [RRO] 3.2.1 Update Readmes (#153)


@revodavid<https://github.com/revodavid> - is this still the right email address and info?
Revolution R Open team at Revolution Analytics by emailing
open@revolutionanalytics.com<mailto:open@revolutionanalytics.com>."

**Comment by j-martens** [comment]
README.md still needs to be updated with new build information for SLES builds.
