### ISSUE TITLE
Source tarball job includes relocatable installs for 3.2.1 

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#155]
Updated source bundle to capture the changes for the relocatable install.

**Comment by j-martens** [comment]
Update the job to include the relocatable pieces please.

**Comment by nathansoz** [comment]
If we use the github zip file then this will be included.

**Comment by j-martens** [comment]
Check source in github.

**Comment by j-martens** [comment]
Tracking in testing spreadsheet with @richcalaway
