### ISSUE TITLE
Fixed repository snapshot date hardcoded in startup message

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#158]
[Reported in the GoogleGroup](https://groups.google.com/forum/#!topic/rropen/aSnf4vJf6aM):

_I've just installed Revolution R Open 3.2.0 on Windows 7 (64 bit).
Currently I prefer to use the most recent CRAN updates.  I've created an .Rprofile file in my home directory that contains:
options(repos = c(CRAN = "http://cran.revolutionanalytics.com"))
However, when I start RRO, I continue to get the message at startup:
"Using CRAN snapshot taken on 2015-05-01"
Should this message not go away when using a regular CRAN archive?
Thanks.  --Dale_

**Comment by j-martens** [comment]
It appears that the fixed repository date is hardcoded into the startup message.

**Comment by revodavid** [comment]
Unfortunately, we can't adapt the message if the user sets the repository in .Rprofile, because `.Rprofile` runs *after* `.Rprofile.site`.

The best we can do is to improve the message to emphasize that this is the default (which may have been overruled by the user.)

**Comment by j-martens** [comment]
Ready for QA.

**Comment by sfweller** [comment]
Still waiting for a new build of RRO 3.2.1 for Windows - not available yet.

**Comment by sfweller** [comment]
Got new Windows build last night - retesting issue today.

**Comment by sfweller** [comment]
Original issue fixed in 6/22/15 Windows RRO 3.2.1 installer.
