### ISSUE TITLE
SLES 11 Support for 8.0.3

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#159]
We also need to release 8.0.3 on SLES 11 for the Teradata release.

**Comment by j-martens** [comment]
Depends on an RPM being developed by J Martenstein.

**Comment by j-martens** [comment]
Ready for testing here: http://devstaging.mran.io/archives/#rro803

**Comment by sfweller** [comment]
Tested the installer on SLES11 and ran our basic IOQ tests. All of the critical tests passed, so I am closing this bug.
