### ISSUE TITLE
R GUI appears to hang with long calculation

### ISSUE THREAD

**Issue by sdgilley** [RevolutionAnalytics/RRO#166]
The following code appears to hang when run in the R GUI in Window RR) 3.2.0. The window is masked and the titlebar says (not responding).  Once the code completes, the window returns.  (This particular code runs much faster when MKL is installed, but even then you will see it momentarily appear to hang.)
```
set.seed (1)
m <- 10000
n <-  5000
A <- matrix (runif (m*n),m,n)

# Matrix multiply
matrix <-system.time (B <- crossprod(A))

# Cholesky Factorization
cholesky <-system.time (C <- chol(B))
```

![image](https://cloud.githubusercontent.com/assets/3650506/8011804/b8fc7c14-0b81-11e5-8e49-7fd24fce80d0.png)

**Comment by j-martens** [comment]
Reproducible in CRAN R 3.2.1 although it takes longer for it to appear unresponsive and grayed out in CRAN R 3.2.1.
