### ISSUE TITLE
RRO for Windows should still write to the R-core registry key

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#174]
RRO 3.2.1 should write to both its own custom key (as it does now) and still put the path to R in the R-core registry key so that it behaves as a drop in replacement to CRAN R in RStudio and similar products as well as on the command line.

**Comment by j-martens** [comment]
Ready for QA now.

**Comment by j-martens** [comment]
Andrie reports that he cannot find the registry keys when he downloads the Windows version of 3.2.1 on devstaging today. The directories for R 3.2.1 are missing too. 

Please note that he has chosen to install into a custom location.

![image001](https://cloud.githubusercontent.com/assets/8481597/8654073/c14fba0e-294d-11e5-9e6f-2592f1be2c3e.png)

**Comment by nathansoz** [comment]
Hmm I did an install from Jenkins and it looks fine:

![rro](https://cloud.githubusercontent.com/assets/6821708/8655531/a0f033b2-2946-11e5-819f-56564f51d223.PNG)

However, when I tried to grab the version on devstaging I noticed that the URL was pointing to: https://mran.revolutionanalytics.com/install/RRO-3.2.1-win.exe

I don't think that is the correct URL... it 404s, so I'm not sure how/when @andrie downloaded from devstaging.

**Comment by j-martens** [comment]
I just updated those URLS to use HTTPS to test something. Those links won't work.
Andrie downloaded from earlier using devstaging.mran.io/install/RRO-3.2.1-win.exe
- Josée



Empowering enterprises to easily and cost-effectively build high-scale analytics solutions leveraging R

Interested in solving Big Data, Distributed Systems or Machine Learning problems? We're hiring...<http://aka.ms/mljobs-internal>

**Comment by nathansoz** [comment]
Ok, well I need more info from @andrie as to how he installed. Specifically, was he an administrator and did he have the checkbox checked to create registry keys (should be on by default). I just did a custom path install on a clean system and it worked ok.

**Comment by andrie** [comment]
Yes, I was an administrator (although this shouldn’t be necessary).

 

Yes, I left all defaults as they were, except installing into c:/rro rather than the default location. I also re-installed, this time specifically testing if the checkbox was ticked. Finally, the MKL installed, so I am assuming this means the keys are picked up from somewhere?

**Comment by nathansoz** [comment]
Being an administrator is needed for the keys to be installed where you are looking (HKLM is a system-wide keystore). 

If the MKL installed that means that the keys were picked up... can you try restarting regedit and seeing if they exist.

**Comment by andrie** [comment]
I think I see what is happening now.

R and RRO uses the same key (IIUC) - so when I installed R after installing RRO, the registry keys disappear.

This doesn't seem optimal.

Can we install the RRO key under /R-core/RRO, for example?

**Comment by nathansoz** [comment]
This was the desired behavior requested by the product team. I think the driving factor was RStudio picking up on the latest version of R installed (be it RRO or R)

**Comment by andrie** [comment]
My point is that RStudio doesn't pick it up.

To get RStudio to recognize RRO, I need to manually point to the file location where RRO is installed.

So, I agree with the product requirement, but I think we should reconsider the implementation options.

Including @revodavid

**Comment by nathansoz** [comment]
My understanding is that RStudio picks up whatever was installed last. So if you install RRO and then R it will pick up R. If you installed R and then RRO, it will pick up RRO.

My understanding is that you are seeing the above behavior.

**Comment by andrie** [comment]
Yes, precisely.  That is undesired behaviour, in my view.

If we design the key to look slightly different, then GNU R and RRO will not interfere with one another.

**Comment by nathansoz** [comment]
How the feature is working now is a consequence of the line in @j-martens comment above: RRO 3.2.1 should write to both its own custom key (as it does now) and still put the path to R in the R-core registry key

At one point I had changed the registry key we wrote to R-core to have RRO in the name and I was told that was not what we wanted to do and that we wanted the overwriting behavior.

**Comment by andrie** [comment]
Then we have to take the debate back to the dev team.

I agree with your original design.

This is what I came up with, and it works for me:

![registry](https://cloud.githubusercontent.com/assets/479998/8660819/25a71792-29ab-11e5-8068-f1261363844a.PNG)

![rstudio](https://cloud.githubusercontent.com/assets/479998/8660838/3b18f7d0-29ab-11e5-8fe4-ac620dc47fc9.PNG)

**Comment by revodavid** [comment]
This is intended behavior. The desired behavior is that RRO modifies the R registry key to point to the RRO executable.

If a user installs RRO and then runs RStudio, it will pick up RRO.
If a user *then* installs CRAN R, RStudio will pick up CRAN R.

This is as intended.

# David

--
David M Smith <davidsmi@microsoft.com<mailto:davidsmi@microsoft.com>>
R Community Lead, Revolution Analytics (a Microsoft company)
Tel: +1 (312) 9205766 (Chicago IL, USA)
Twitter: @revodavid<http://twitter.com/revodavid> | Blog:  http://blog.revolutionanalytics.com<http://blog.revolutionanalytics.com/>
We are hiring engineers<http://azuremljobs.github.io/> for Revolution R and Azure Machine Learning.

**Comment by andrie** [comment]
RStudio in fact picks up "all" installations of R, including all old installations. This is why R and RRE easily sits side by side.

Somehow RStudio uses the last installed version as the default.

However, RRO breaks this paradigm, since it doesn't show up in the list of installed versions.

In my view, this is highly undesirable.

And it is easy to fix.

**Comment by revodavid** [comment]
I suspect RStudio looks at all *distinct* versions of R, but RRO and R can both be installed with the same R version. That’s something RStudio probably doesn’t recognize, so we’ll have to accept that it will use the last installed R or RRO of a specific R engine number.

# David

--
David M Smith <davidsmi@microsoft.com<mailto:davidsmi@microsoft.com>>
R Community Lead, Revolution Analytics (a Microsoft company)
Tel: +1 (312) 9205766 (Chicago IL, USA)
Twitter: @revodavid<http://twitter.com/revodavid> | Blog:  http://blog.revolutionanalytics.com<http://blog.revolutionanalytics.com/>
We are hiring engineers<http://azuremljobs.github.io/> for Revolution R and Azure Machine Learning.

**Comment by andrie** [comment]
My point is we don't have to accept this.

Both Nathan and I have a solution that works in the way that every R user will recognize and expect.

Please see my screen shots.  I defined both versions in the registry, and RStudio recognises both.

**Comment by richcalaway** [comment]
But would this work with, say, RExcel?

**Comment by andrie** [comment]
That is a very important question and should be answered once we evaluate this.

@revodavid and I discussed this last night. I think I have persuaded him that this is important enough to spend some time on in a future design cycle.

**Comment by j-martens** [comment]
Things to stay as they are for RRO 3.2.1 release. Re-evaluate for 3.2.2 or beyond.
