### ISSUE TITLE
RRO 8.0.3 Win - uninstall leaves 'checkpoint' directory

### ISSUE THREAD

**Issue by daleq** [RevolutionAnalytics/RRO#181]
After uninstalling RRO 8.0.3 for Windows, the directory
C:\Program Files\RRO\R-3.1.3\library\checkpoint
is still populated with files/directories.

**Comment by j-martens** [comment]
Related to https://github.com/RA-Internal/MRAN-site/issues/220

**Comment by j-martens** [comment]
Handled in the documentation now.
