### ISSUE TITLE
Please include steps to install on Raspberry Pi

### ISSUE THREAD

**Issue by vikasgupta1812** [RevolutionAnalytics/RRO#186]
Please include steps to install on Raspberry Pi. I am trying to build it from source with limited success.

**Comment by nathansoz** [comment]
Hi @vikasgupta1812,

Can you elaborate on what you have done to try to build? If you could post the console out that you get when you try to build, as well as the commands you are running, that would be great!

**Comment by vikasgupta1812** [comment]
Hi Nathan, I was able to finally install it successfully yesterday. It
involved installing lot of libraries. I am still working on installing
RStudio, its a very slow process.
