### ISSUE TITLE
Use HTTPS to download packages by default

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#187]
For security, RRO should always download packages via HTTPS.

Change the default CRAN mirror to `https://mran.revolutionanalytics.com/snapshot/SNAPSHOTDATE`

Configure R to allow use of HTTPS to download files (required for use of download.packages with an HTTPS mirrror):

Windows: `options(download.file.method = "wininet")`
OS X and Linux: `options(download.file.method = "libcurl")`
(Note: libcurl must be compiled in to RRO. See https://support.rstudio.com/hc/en-us/articles/206827897 )

**Comment by nathansoz** [comment]
This requires a build change. Libcurl is not a default package on most ubuntu distributions, so it needs to be added to the build systems.
