### ISSUE TITLE
RRO 3.2.1 for Windows needs a signed certificate

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#188]

**Comment by j-martens** [comment]
Both Andrie and David S had issues installing on Windows.

When DS downloaded today and attempted to install on Windows. He got the following warning and could not install.

"Windows SmartScan prevented an unrecognized app from starting. Running this app might put your PC at risk"

**Comment by nathansoz** [comment]
Signtool.exe was missing from the new windows build server. I've dropped it in place and kicked off a build. I've verified that the new RRO binary on devstaging is signed.
