### ISSUE TITLE
Package bundler

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#189]
Create a system to make it possible to bundle R packages with RRO, and install them with RRO.

Suggested implementation:
* Create a "package manifest" file, specifying packages to include
 * Manifest file specifies for each package:
  * Package Name
  * Location of source bundle for package (e.g. `http://mran.revolutionanalytics.com/snapshot/2015-07-13/src/contrib/checkpoint_0.3.10.tar.gz`)
* Create a process to build a source bundle from:
 * R source code
 * Package source code (from manifest)
 * Any package dependencies (from manifest)
 * Use this bundle for the RRO source download
* Build RRO and packages from source bundle
 * Include bundled packages in default package library

**Comment by j-martens** [comment]
Associated with 
#181 
#130
https://github.com/RA-Internal/MRAN-site/issues/220
