### ISSUE TITLE
AzureMLclient package to interface with Azure ML datasets

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#192]
Create and bundle with RRO a package to interface R with datasets published to Azure ML.

Python has an equivalent package: https://github.com/Azure/Azure-MachineLearning-ClientLibrary-Python

This package can be used directly by R users, and will also be used to support the [Get Data Access Code](http://blogs.technet.com/b/machinelearning/archive/2015/03/19/azure-ml-now-with-even-more-python.aspx) feature for R in Azure ML, and a similar feature in Jupyter Notebook.

**Comment by andrie** [comment]
The package lives at https://github.com/RA-Internal/azureml
