### ISSUE TITLE
Set snapshot to aug 27, 2015

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#203]
Update the fixed snapshot date to Aug 27, 2015 for this release.

~~~Update the fixed snapshot date to Sept 1, 2015 for this release.~~~

**Comment by richcalaway** [comment]
Created a pull request to update this to Aug 24 for now; will update to Sept 1 next week.

**Comment by j-martens** [comment]
Going back to Aug 27th.
