### ISSUE TITLE
Create Windows uninstaller for RRO

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#208]
It is relatively important that we create a good uninstaller as this will be required for SQL Server. 

Also related to #194 and #143

**Comment by richcalaway** [comment]
Per Nathan, with the bundling of packages, the standard uninstall procedure will now remove everything we install, so there is no need for a separate uninstaller.

**Comment by j-martens** [comment]
Still needed due to https://github.com/RevolutionAnalytics/RRO/issues/143
