### ISSUE TITLE
MKL Install Error

### ISSUE THREAD

**Issue by LGSuresh** [RevolutionAnalytics/RRO#214]
I installed R-3.2.1 under a User folder. Then I tried to install MKL (RevoMath - 3.2.1) and I get the following error:
"RRO 3.2.1 could not be detected. The installer will not be able to detect RRO if RRO was installed with the option to "Save version number in registry" unchecked. Please install RRO with this option enabled."

I had the "Save version number in registry" checked when I did the RRO install. Not sure where the MKL installer is looking. Can anyone help?

**Comment by j-martens** [comment]
Hello, 
Thanks for your report. Another great place for questions is our [Google Group forum](https://groups.google.com/forum/#!forum/rropen).

In fact, [here is a thread](https://groups.google.com/forum/#!searchin/rropen/registry/rropen/5FSI-Djh4gs/B2U-u8CVCwAJ) similar to your experience.  I think they rebooted and then it worked.

Can you [post your question here](https://groups.google.com/forum/#!newtopic/rropen) and let us know what version of Windows you are running please and if rebooting worked or not?

Thanks!

**Comment by LGSuresh** [comment]
I had rebooted multiple times. But that didnt seem to help. I am using Windows 7. Let me post the question in the google forum.

**Comment by j-martens** [comment]
Hello again, I just reread your original post. Did you install R 3.2.1 from CRAN or RRO 3.2.1? Our MKL installer is customized for RRO only. Thanks.

**Comment by LGSuresh** [comment]
I installed RRO 3.2.1

**Comment by sfweller** [comment]
Hello - this is a known issue when installing on Windows as a non-administrative user.
The MKL installer requires admin privleges on Windows systems and will fail if you install to a user-specific folder.

The workaround is to have someone with administrator privileges perform the install. Unfortunately, their is not a better workaround for this problem at the moment.

Stephen Weller
Revolution R Open Technical Support

**Comment by LGSuresh** [comment]
Thank you so much for your reply. You are right. I do not have administrator privileges to my system.
