### ISSUE TITLE
BUILD_ID not found error

### ISSUE THREAD

**Issue by rafsanm** [RevolutionAnalytics/RRO#217]
Tried building v3.2.1. It builds successfully and is functional, but I keep seeing this at startup : 

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

**Error in structure(list(major = "3", minor = "2.1", `build id` = BUILD_ID),  : 
  object 'BUILD_ID' not found**

**Comment by revobuil** [comment]
Try changing BUILD_ID to "1" (including the quotes). We are currently fixing the build system to make it easier for people to consume. This is one artifact that I'll be sure to fix in the next iteration.

Sent from my Windows Phone
________________________________

**Comment by rafsanm** [comment]
Yes this works (I previously built using "N/A").
