### ISSUE TITLE
RRO 3.2.2 Installer names are inconsistent / wrong version number

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#229]
Many installers currently have the same name. We could not put them up on our website like this without overwriting them.

Also, names have inconsistent use of lowercase and uppercase.

Finally, the version numbers in the filenames do not match the version numbers for this release.

| Platform | Current Name | Proposed Name |
| ---- | ---- | ---- |
| CentOS / RHEL 5 | RRO-3.2.2-1.x86_64.rpm | RRO_3.2.2-el5.centos.x86_64.rpm |
| CentOS / RHEL 6 | RRO-3.2.2-1.el6.x86_64.rpm  | RRO_3.2.2-el6.centos.x86_64.rpm |
| CentOS / RHEL 7 | RRO-3.2.2-1.el7.centos.x86_64.rpm |  RRO_3.2.2-el7.centos.x86_64.rpm |
| openSUSE 13.1 | RRO-3.2.2-1.x86_64.rpm	 |  RRO_3.2.2-openSUSE-13.1.x86_64.rpm |
| SLES 10 | RRO-3.2.2-1.x86_64.rpm |  RRO_3.2.2-SLES10.x86_64.rpm |
| SLES 11 | RRO-3.2.2-1.x86_64.rpm |  RRO_3.2.2-SLES11.x86_64.rpm |
| Ubuntu-12 | rro_3.2.2-2_amd64.deb |  RRO_3.2.2-Ubuntu-12.04_amd64.deb  |
| Ubuntu-14   | rro_3.2.2-2_amd64.deb | RRO_3.2.2-Ubuntu-14.04_amd64.deb |
| Ubuntu-15   | rro_3.2.2-2_amd64.deb |  RRO_3.2.2-Ubuntu-15.04_amd64.deb |
| Windows  | R-3.2.2-win.exe	  | RRO_3.2.2-Win.exe |
|  OS X  | n/available yet   | RRO_8.0.3-OSX.pkg  |

**Comment by richcalaway** [comment]
el6 and el7 are fairly standard identifiers for RHEL/CentOS 6 and 7 respectively; we've been using them in many of our download file names for awhile now. The Ubuntu deb files are named correctly according to the Debian naming conventions; this is of course problematic for the reasons you mention. This is perhaps a compelling reason to bundle the rpm/deb files into a tar.gz file for which we can use arbitrary naming conventions.

**Comment by revodavid** [comment]
A better solution would be to store the binaries in folders by architecture (sles10/, sles11/ etc) and keep these names as they match the naming conventions.

# David

--
David M Smith <davidsmi@microsoft.com<mailto:davidsmi@microsoft.com>>
R Community Lead, Revolution Analytics (a Microsoft company)
Tel: +1 (312) 9205766 (Chicago IL, USA)
Twitter: @revodavid<http://twitter.com/revodavid> | Blog:  http://blog.revolutionanalytics.com<http://blog.revolutionanalytics.com/>
We are hiring engineers<http://azuremljobs.github.io/> for Revolution R and Azure Machine Learning.

**Comment by richcalaway** [comment]
The names are all unique now...
