### ISSUE TITLE
RRO on Ubuntu: Missing libraries. Error in RStudioGD()

### ISSUE THREAD

**Issue by j-martens** [RevolutionAnalytics/RRO#233]
Two google group users reported the following:

Mariano Rico 	
Aug 27

I have installed RRO 3.2.1 in an Ubuntu machine in which there was an CRAN R version and RStudio.
I see that /usr/bin/R now points to the RRO (/usr/bin/R --> /usr//lib64/RRO-3.2.1/R-3.2.1/lib/R/bin/R ) and the starting message in Rstudio informs that it is using the RRO version with MKL.

However, when I try to plot something as simple as 

plot(1:10)

I get this error

Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (R code execution error)
In addition: Warning message:
In grDevices:::png("/tmp/RtmpR8RPl1/452e73a80ef34f46977c4cc704c4b35d.png",  :
 unable to open connection to X11 display ''

I have installed additional Ubuntu packages like the following ones with no results (of course, I restarted Rstudio after any instalation)
sudo apt-get install libx11-dev libxt-dev libpango1.0-dev r-cran-cairodevice

I am using a machine without display, but I did this previously on other similar machine without any problem.
In some forum I read that perhaps I have to compile RRO from sources with flags for not using xlib.
Do you have any information about this?

Best regards,

-Mariano
Click here to Reply

Le Big Z 	
Aug 27

Same here, running RStudio Server on Ubuntu 14.04 on a headless VM. I only get this Error on RRO 3.2.1, when i run the RRO 3.2.0 it does not occur:

$ /usr/lib64/RRO-3.2.0/R-3.2.0/bin/R
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE        TRUE        TRUE       FALSE        TRUE       FALSE
$ /usr/lib64/RRO-3.2.1/R-3.2.1/bin/R
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE        TRUE       FALSE       FALSE        TRUE        TRUE

**Comment by j-martens** [comment]
Turns out that the Ubuntu build machine doesn’t have all the development libraries needed. Specifically, cairo tiff and jpeg are missing. Consequently, with capabilities(), those come up as FALSE.  Fix in upcoming 3.2.2 release.

**Comment by richcalaway** [comment]
Believe this is fixed now...we no longer have issues with png().

**Comment by MarianoRico** [comment]
Yes, with RRO 3.2.1 y got
> capabilities()
      jpeg         png        tiff       tcltk         X11        aqua
     FALSE       FALSE       FALSE        TRUE       FALSE       FALSE
     ...

And now, with RRO 3.2.2 y get 
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE

However, now I get a new problem: Rstudio does not start :-((
I get these error messages is /var/log/syslog

> ERROR Unable to determine R home directory; LOGGED FROM: bool rstudio::core::r_util::{anonymous}::detectRLocationsUsingScript(const rstudio::core::FilePath&, rstudio::core::FilePath*, rstudio::core::FilePath*, rstudio::core::config_utils::Variables*, std::string*) /home/ubuntu/rstudio/src/cpp/core/r_util/REnvironmentPosix.cpp:435

> ERROR R did not return any output when queried for directory location information; Unable to determine R home directory; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/server/ServerMain.cpp:402

**Comment by sfweller** [comment]
Hi Mariano,

This can be normal behavior with Rstudio on Ubuntu.

Please try the following(this worked for me):

1).  From a Linux shell prompt, type:   
%export RSTUDIO_WHICH_R=/usr/bin/R

2).  Make sure that a link '/usr/bin/R' exists in your install and points to the following:
      /usr//lib64/RRO-3.2.2/R-3.2.2/lib/R/bin/R

3).  Make sure that port 8787 is open on your system.

4).  Open a web browser and point it to:
      http://<your.ip.address>:8787

This should open Rstudio with a login prompt.

5).  If you want to permanently set the environment variable, 'RSTUDIO_WHICH_R' add it to your .bash_profile file in your user home directory.


Stephen Weller
Revolution R Open Technical Support
