### ISSUE TITLE
RRO "broken" after lib32-icu update from 55 to 56

### ISSUE THREAD

**Issue by irkonik** [RevolutionAnalytics/RRO#248]
RRO can't start since I've updated lib32-icu (unicode "stuff") from 55 to 56.
The error message: 
```bash
/usr/lib/RRO-3.2.2/R-3.2.2/lib64/R/bin/exec/R: error while loading shared libraries: libicuuc.so.55: cannot open shared object file: No such file or directory
```
It tries to connect to the old binaries. Downgrading lib32-icu is not possible, it would break my system.

Any idea how to fix it?

**Comment by j-martens** [comment]
Hello. Thanks for your report. What OS, platform and version are you using? And please share how you went about updating lib32-icu? Thanks.

**Comment by irkonik** [comment]
ARCH Linux x86, testing branch. Updated it via pacman, from 55 to the next higher version.
It's my mistake by me, don't get me wrong, classic case of PEBKAC. But the question is why it can't utilize the newer binaries.
They can't have changed that much. Re-install didn't fix it sadly.

**Comment by j-martens** [comment]
We don't provide binaries for arch Linux. Did you compile RRO from source?

**Comment by irkonik** [comment]
I fiddled around some more and fixed it somewhere along the way of removing everything associated with RRO, removing and installing lib32-icu, installing RRO, revomath and openblas again. I have no clue why it worked this way and not before. Sorry for causing trouble, panicked a little when it didn't want to work and the classic remove & install didn't work. 

Cheers, and thank you very much. Such an awesome project!

**Comment by j-martens** [comment]
Glad to hear it.
