### ISSUE TITLE
installation process failed on Ubuntu 14 - a bug in RevoMath.sh?

### ISSUE THREAD

**Issue by jangorecki** [RevolutionAnalytics/RRO#265]
Following the current installation docs on https://mran.revolutionanalytics.com/documents/rro/installation/
When installing RRO + RevoMath on Ubuntu 14.04 having base R version 3.2.2 (2015-08-14) I've hitting the following blocker after successfully installing RRO and trying to install RevoMath running `./RevoMath.sh`.
```
Do you accept the terms in the license agreement (y or n)? y
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
/usr//lib64/RRO-3.2.2/R-3.2.2/lib/R/bin/R: line 215: /etc/ldpaths: No such file or directory
ERROR: R_HOME ('') not found
Error: Revolution R Open was detected; however, it is not the correct version.
This utility is for version 3.2.2 only.  Exiting now.........
```
Already tried to setup `R_HOME` both to RRO directory and to default R directory, doesn't make any difference.

The official docker image for RRO was not updated for the latest version, so there is not live install docs: https://github.com/RevolutionAnalytics/Docker-RRO/

It looks like a bug somewhere in `RevoMath.sh`.

**Comment by j-martens** [comment]
Could you please try this?
 
ls -l /bin/sh
 
If this returns something OTHER than a symbolic link /bin/bash, do this:
 
sudo rm /bin/sh
sudo ln -s /bin/bash /bin/sh

**Comment by jangorecki** [comment]
I tried.
```sh
ls -l /bin/sh
# lrwxrwxrwx 1 root root 9 Jan 12 21:29 /bin/sh -> /bin/bash
```
Error didn't go away.

----

Fully reproducible script below.

- Fast run Ubuntu14 + r-base-dev 3.2.2:
```sh
docker run -it jangorecki/r-base-dev bash
```

- installation nside your Ubuntu:
```sh
apt-get update
apt-get install -y curl
curl -O https://mran.revolutionanalytics.com/install/RRO-3.2.2-Ubuntu-14.4.x86_64.deb
dpkg -i RRO-3.2.2-Ubuntu-14.4.x86_64.deb
curl -O https://mran.revolutionanalytics.com/install/RevoMath-3.2.2.tar.gz
tar -xzf RevoMath-3.2.2.tar.gz
cd RevoMath
sudo rm /bin/sh
sudo ln -s /bin/bash /bin/sh
# `ls -l /bin/sh` at this point results in `/bin/sh -> /bin/bash`
./RevoMath.sh
```

**Comment by fred777** [comment]
I suspect you have left-over files from a previous install.

Try to delete /usr/lib64/RRO-3.2.2/R-3.2.2/lib/R/library/RevoUtilsMath/

**Comment by jangorecki** [comment]
I've tried on plain Ubuntu docker image without regular R, same error.

**Comment by j-martens** [comment]
MRO 3.2.3 was just released. Can you try a clean install of MRO 3.2.3 with the 3.2.3 MKLs?

**Comment by jangorecki** [comment]
Didn't help, fully reproducible script on latest image of Ubuntu 14.04 and latest MRO.
```sh
docker pull ubuntu:14.04
docker run -it --name mro-test ubuntu:14.04 bash
apt-get update
apt-get install -y curl
curl -O https://mran.revolutionanalytics.com/install/mro/3.2.3/MRO-3.2.3-Ubuntu-14.4.x86_64.deb
apt-get -f install -y
dpkg -i MRO-3.2.3-Ubuntu-14.4.x86_64.deb
curl -O https://mran.revolutionanalytics.com/install/mro/3.2.3/RevoMath-3.2.3.tar.gz
tar -xzf RevoMath-3.2.3.tar.gz
cd RevoMath
rm /bin/sh
ln -s /bin/bash /bin/sh
ls -l /bin/sh
# lrwxrwxrwx 1 root root 9 Jan 22 14:40 /bin/sh -> /bin/bash
./RevoMath.sh
## ... license agreement ...
#Do you accept the terms in the license agreement (y or n)? y
#dirname: missing operand
#Try 'dirname --help' for more information.
#dirname: missing operand
#Try 'dirname --help' for more information.
#/usr//lib64/MRO-3.2.3/R-3.2.3/lib/R/bin/R: line 215: /etc/ldpaths: No such file or directory
#ERROR: R_HOME ('') not found
#Error: Microsoft R Open was detected; however, it is not the correct version.
#This utility is for version 3.2.3 only.  Exiting now.........
R
#dirname: missing operand
#Try 'dirname --help' for more information.
#dirname: missing operand
#Try 'dirname --help' for more information.
#/usr/bin/R: line 215: /etc/ldpaths: No such file or directory
#ERROR: R_HOME ('') not found
R --help
#dirname: missing operand
#Try 'dirname --help' for more information.
#dirname: missing operand
#Try 'dirname --help' for more information.
#
#Usage: R [options] [< infile] [> outfile]
#   or: R CMD command [arguments]
#
#Start R, a system for statistical computation and graphics, with the
#specified options, or invoke an R tool via the 'R CMD' interface.
#
#Options:
#  -h, --help            Print short help message and exit
#  --version             Print version info and exit
## ... rest of options
```
btw. aren't there any plans to provide an official MRO docker image?

**Comment by sfweller** [comment]
I now got the latest MRO(3.2.3) to work with the latest Docker Ubuntu image for 14.04. One problem is that this docker image does not contain all of the tools necessary to install the RevoUtilsMath package, that is needed for MKL to work with MRO.

Please check the file 'mkl_log.txt' in the RevoMath folder that gets created after untarring the RevoMath-3.2.3.tar.gz file. That contains useful information as to why the RevoMath package install fails.

I had to do the following, to get things to work:
1). Run RevoUtilsMath.sh and select option '2' to Uninstall the MKL.  
2). Run the following commands from bash shell prompt:

        apt-get install make
        apt-get install gcc

3).  The try running 'RevoMath.sh' again.


Hope this helps.

Stephen Weller
Microsoft R Open Technical Support

**Comment by jangorecki** [comment]
@sfweller Thanks, great you've found solution.
I would suggest to check those dependencies in shell script.
Also mentioned official docker image would be very useful as it is the fastest way to just try a product.

Is the repository of `revolutionanalytics.com/documents` available somewhere? I would like to track changes on the installation docs webpage.

**Comment by nuest** [comment]
@jangorecki  I've created a Docker image, maybe it can be of help for you: https://github.com/nuest/docker-mro

My issue is that building the image worked on my machine, but not on Docker Hub, wich a similar message as yours: https://hub.docker.com/r/nuest/docker-mro/builds/bhqbu7n7pcwh573ftwyuyrb/

But hopefully you can build the image locally and it is of use.

**Comment by jangorecki** [comment]
@nuest this will definitely be helpful, as it gives working example! Thanks for sharing.
I think the issue can be closed already.

**Comment by nuest** [comment]
Yes - issue can be closed. Just a quick update though: Image was successfully pushed to Docker Hub: https://hub.docker.com/r/nuest/docker-mro/
