### ISSUE TITLE
MRO-3.2.3 mac does not create a shell R executable

### ISSUE THREAD

**Issue by rebelwarrior** [RevolutionAnalytics/RRO#271]
`which R` produces nothing on a clean install of MRO. (El Capitan)

I think this only happens on a clean install. I did an upgrade on another computer and it either preserved (or did install) the command line executable at `/usr/bin/R` However a clean install created no command line options.

**Comment by sfweller** [comment]
This is a known issue. The new version of MRO currently does not create a '/usr/bin/R' link on the Mac. You will need to create it manually using the 'ln' command:

For example:
ln -s /Library/Frameworks/R.framework/Resources/bin/R /usr/local/bin/R

If you create this link, then the command 'system("which R")' will work in MRO.
I am not sure why we no longer create the link in '/usr/bin', but we will consider that for the next release.

Stephen Weller
Microsoft R Open Technical Support

**Comment by rebelwarrior** [comment]
Thanks.

**Comment by j-martens** [comment]
Hello,

We have re-released Microsoft R Open 3.2.3 for OS X with a fix for this. You can download it from here: https://mran.microsoft.com/download/

Thanks,
Josée
