### ISSUE TITLE
MRO 3.2.3 Windows RGui crash when typing characters beyond width of resized window

### ISSUE THREAD

**Issue by mekkim** [RevolutionAnalytics/RRO#273]
MRO 3.2.3 64-bit Windows clean install (after uninstalling all previous versions of RRO/R) crashes when typing characters beyond the GUI's current width if the RGui window is made vertically longer.  The error is as follows: 

Unhandled exception at 0x000007FEFEB87D0F (msvcrt.dll) in Rgui.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

My quick search links msvcrt.dll to Visual C++ redistributable.  Does MRO 3.2.3 depend on a particular version of Visual C++ redistributable that isn't packaged with it?

Steps to reproduce:

- OS Win7 Ultimate 64-bit SP1 - 64 GB Ram - Core i7-5930K CPU
- Previously running R 3.2.3 core without issue / Previously running RRO 3.2.0 without issue
- Uninstall all previous versions of RRO/R and manually delete remaining install directories.  Reboot.
- Install MRO 3.2.3 Windows using default installer found here: https://mran.revolutionanalytics.com/download/  - with default settings
- Launch MRO 3.2.3
- Increase size of RGui window vertically so that it's slightly larger (or full height, or full screen - Basically, change the vertical height of the window by at least 10%)
- Type commands or characters until they reach the right edge of the RGui window
- MRO will crash and report the above error upon launching debugger

Troubleshooting attempted: 
- Uninstalled and reinstalled multiple times
- Installed latest versions of Visual C++ redistributable (2008, 2010, 2012, 2013, x64)
- Happens without RevoMath installation 
- Reinstalled base R 3.2.3 -> No issue.  Only occurs with MRO 3.2.3
- Tested with different sizes of RGui window.  Works fine if the default size of the window is left untouched.  Crashes begin after the window is made vertically larger by at least 10%, or full screen, or full height, or similar measures in between.  Horizontal resizing of the window has no effect.  /Shrinking/ the vertical size of the window to smaller than default size has no effect.

- Enabling "Prevent windows from being automatically arranged..." in control panel has no effect

**Comment by j-martens** [comment]
Thanks for your report. You can track progress here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rropen/iuW1XRarPPs/SQMzLkF0CwAJ

**Comment by j-martens** [comment]
Hello,

We have re-released Microsoft R Open 3.2.3 for Windows with a fix for this. You can download it from here: https://mran.microsoft.com/download/

Thanks,
Josée

**Comment by mekkim** [comment]
I have downloaded the re-released version of MRO 3.2.3 for Windows.  The RGui crash has been resolved in Windows 8.1, but is still occurring in Windows 7.  The behaviour of the RGui window is the same as before (when  resizing, the line seems to jump to a lower line, breaking in the middle) and crashes in the same way.  I've tried numerous compatibility settings and cannot get it to work.  Please reopen this issue as it is not yet resolved fully.

**Comment by mekkim** [comment]
UPDATE: After much testing, I have located the specific source of the issue.  The culprit is the line for `rows = XX` in the `Rconsole` parameters file under `Dimensions (in characters of the console.`  The RGui will crash when resized if the value `XX` is less than the number of lines that are displayed on RGui startup, i.e., R version number, Copyright, Platform, Free software disclaimer, etc. etc.,  

The reason this crash was only occurring in MRO and not base R was because MRO pushes MORE lines to the the RGui console at startup (26 vs 19 for Base R).  As such, users who had `row = 25` in their `RConsole` settings, which was an old default from years ago, would see the crash in MRO but not Base R.  Increasing the setting to 27 or higher, prevents the crash.  Incidentally, setting the `row = ` value to 18 or less will ALSO crash Base R, suggesting that it isn't, in fact, an MRO problem.  I will report it to the RCore team.

In sum, the workaround is that users installing MRO must update any old RConsole preference files to have `row = 27` or higher.  Ideally, the MRO installer would look for this line in default locations, but that's a bit complicated and unnecessary if the RCore team fixes the underlying issue.  Further, if the amount of text pushed by MRO to the RGui console at launch ever increases (such as with additional instructions, etc.), the `row = xx` value will have to be increased accordingly to avoid crashes.

**Comment by nathansoz** [comment]
We have provided a fix to Cran for the underlying issue and expect it will be incorporated in the next release of R.

**Comment by mekkim** [comment]
@nathansoz - Ah, excellent.  Thanks for that!  At least I can get working now by changing my RConsole file. :)

**Comment by nathansoz** [comment]
I believe we adjusted the default console file to have 35 lines as a workaround in the rerelease. I'm surprised that the console file you got from the rereleased installer didn't have that fix...

@j-martens can you test on Windows 7 and see if you can reproduce the issue still?

**Comment by mekkim** [comment]
@nathansoz  You did adjust it to 35.  The thing is that Base R (and MRO) look in two default locations for an RConsole:  `c:/Program Files/Microsoft/MRO/R-3.2.3/etc/` folder or the equivalent install location and `c:/users/<username>/documents/` - The latter overrides the former if it's present.  I keep my RConsole file in the latter so that both MRO and Base R can use it, so its `row` value remained at 25 even with the re-release.

**Comment by mekkim** [comment]
I see your fix here: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16698 - Awesome!  That should do it!  Thanks!
