### ISSUE TITLE
Install from source on linux fails

### ISSUE THREAD

**Issue by krz** [RevolutionAnalytics/RRO#297]
Hi,
I tried to install MRO on a linux cluster in my home directory where I do not have root access:
this is the error message I get when I execute build.sh.

I have no problems building open source R from source on this machine.

GC Warning: Limiting number of mark threads
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v1.1.4322

** (nuget.exe:13744): WARNING **: The class System.Collections.Generic.IEnumerable`1 could not be loaded, used in mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

Unhandled Exception: System.TypeLoadException: Could not load type 'NuGet.Program' from assembly 'NuGet, Version=2.8.60717.93, Culture=neutral, PublicKeyToken=null'.
~/RRO-3.2.3-1/RRO-src/buildFiles ~/RRO-3.2.3-1
GC Warning: Limiting number of mark threads
XBuild Engine Version 2.6.7.0
Mono, Version 2.6.7.0
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2009.
/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln:  warning : /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: Unknown toolsversion: 12.0

Build started 4/7/2016 9:00:45 AM.
__________________________________________________
Project "/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln" (default target(s)):

	Target ValidateSolutionConfiguration:
		Building solution configuration "Release|Any CPU".

	Target Build:
/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln: error : Error building project /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: Unknown toolsversion: 12.0
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln".-- FAILED

Done building project "/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln".-- FAILED

Build FAILED.

Warnings:

/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln:  warning : /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: Unknown toolsversion: 12.0

Errors:

/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln (default targets) ->
(Build target) ->

	/home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RRO_build.sln: error : Error building project /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: /home/igm/c/RRO-3.2.3-1/RRO-src/buildFiles/RevoUtils/RevoUtils.csproj: Unknown toolsversion: 12.0

	 1 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.0378090
GC Warning: Limiting number of mark threads
Cannot open assembly 'packages/FAKE.4.0.3/tools/FAKE.exe': No such file or directory.
~/RRO-3.2.3-1

**Comment by sfweller** [comment]
Can you please tell us what version of Linux you are installing on(Redhat, Ubuntu or SLES) and the version number of OS?

Thanks.

Stephen Weller
Microsoft R Open Support Engineer

**Comment by krz** [comment]
this is on SLES 11

**Comment by nathansoz** [comment]
Hi @krz. We've moved repositories to here: https://github.com/Microsoft/microsoft-r-open

You can actually just build the R source code using configure/make/make install after patching with the included .patch files in the repository.
