### ISSUE TITLE
Install MKL Error - Linux ubuntu 15.04

### ISSUE THREAD

**Issue by ToledoEM** [RevolutionAnalytics/RRO#306]
I uninstalled MRO and MKL on Ubuntu 15.04. The instalation of MRO3.2.4 goes ok, but on the installation of the MKL there is an error when I run RevoMath.sh
               
`Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: fun(libname, pkgname)
  error: To use RevoUtilsMath you must first install the MKL Math Library.
 Visit http://mran.revolutionanalytics.com/download.
 If you have previously installed the MKL Math Library,
remove it and then re-install.
Error: package or namespace load failed for ‘RevoUtilsMath’
Execution halted
Error: Microsoft R Open was detected; however, it is not the correct version.
This utility is for version 3.2.4 only.  Exiting now.........`

   
I do not know how to continue.

**Comment by sfweller** [comment]
It looks like the installer detected a old version of Revolution R Open on your system, so it was not able to install the MKL component. You should be able to get past this issue by uninstalling the old version of RRO and then installing the MKL component for MRO 3.2.4.

So run:

dpkg --purge rro
rm -rf /usr/lib64/RRO-3.2.2

Then, attempt to run the MKL installer for MRO 3.2.4 again.

Stephen Weller
Microsoft R Open Support Engineer

**Comment by ToledoEM** [comment]
Thank Stephen, that was the first thing that I tried.
