### ISSUE TITLE
g++ package needed on Ubuntu installer

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/RRO#31]
A user reports at [RRO google groups](https://groups.google.com/forum/#!topic/rropen/GeCyC-wfWA4) that `devtools::install_github does not work on Ubuntu`

I am unable to replicate, but there is some indications that this might be related to locale (see https://github.com/twitter/BreakoutDetection/issues/6)

User report:

```
R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

Revolution R Open 8.0 beta
The enhanced R distribution from Revolution Analytics
Visit mran.revolutionanalytics.com/open for information
about additional features and technical support options.

library(devtools)
devtools::install_github("twitter/BreakoutDetection")
Downloading github repo twitter/BreakoutDetection@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
error in running command

Sys.info()
sysname 
"Linux" 
release 
"3.13.0-37-generic" 
version 
"#64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014" 
nodename 
"Inspiron-3520" 
machine 
"x86_64"
```

**Comment by elmerehbi** [comment]
@cmosetick I am on Ubuntu 14.04.3 and having the same problem:

```
devtools::install_github("ropensci/plotly")
Downloading GitHub repo ropensci/plotly@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
```
I already have g++ installed. And I am having this issue with several other packages some of which I was able to install from CRAN.

**Comment by nriesland** [comment]
This should fix the problem

options(unzip = 'internal')

**Comment by elmerehbi** [comment]
@nriesland 

I get the following errors:

```
R >> options(unzip = 'internal')
R >> devtools::install_github("ropensci/plotly") 
Downloading GitHub repo ropensci/plotly@master
Installing plotly
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Error in read.dcf(file = tmpf) : cannot open the connection
```

I should note that packages are being installed under the hoe directory not under root.

**Comment by sfweller** [comment]
This appears to be some kind of certificate problem on your machine.
I can get the command 'devtools:::install_github("ropensci/plotly")' to work fine on my Ubuntu 14.04 system with the latest version of Revolution R Open, 3.2.2.

What version of OS(Ubuntu?) are you installing on?

I suggest that you check out the suggestions in this post:
http://apple.stackexchange.com/questions/95538/how-to-fix-curl-throwing-error-setting-certificate-verify-locations

to see if you can determine what the problem is. It may be a permissions problem with accessing the certs on your system.

Stephen Weller
Revolution R Open Support Engineer

**Comment by elmerehbi** [comment]
As I mentioned earlier I am on Ubuntu 14.04.3.

I checked the directed the certificates are supposed to be in and there's no `certs` directory under `/etc/pki/tls/` . I have `nssdb` only.
