### ISSUE TITLE
no more portability?

### ISSUE THREAD

**Issue by pcava** [RevolutionAnalytics/RRO#311]
The installer for the actual release MRO 3.3.1 doesn't allow to install on a portable usb pen/external drive anymore...I got the message "Installation directory must be on a local hard drive".

Why such change compared to previous versions and current R 3.3.1?

**Comment by revobuil** [comment]
The MRO 3.3.1 installer for Windows is built on WiXhttp://wixtoolset.org/ which disables installation to non-local drives by default. If you wish to override this behavior, you can launch the MRO setup MSI using the following command-line arguments:

```
            msiexec /i <path_to_MSI> WIXUI_DONTVALIDATEPATH=1
```

Please keep in mind this is not a supported scenario which may result in unexpected behavior.

**Comment by pcava** [comment]
Thanks it's working
