### ISSUE TITLE
warning message after start R console.

### ISSUE THREAD

**Issue by taoluo** [RevolutionAnalytics/RRO#312]
MRO  3.3.1.
mac OS X : 10.11.6

```
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libXt.7.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found
```

I already create a symbolic link to /usr/X11 with `sudo ln -s /usr/X11 /opt/X11`

**Comment by taoluo** [comment]
It seems MRO installer assumes XQuartz  is installed in `/opt/X11`. After download and install XQuartz from its website (https://www.xquartz.org), this warning message disappeared.

**Comment by sfweller** [comment]
Yes, this is a known issue and has been documented in the Microsoft R Open 3.3.1 release notes.

Stephen Weller
Microsoft R Product Team
