### ISSUE TITLE
Installation Error: microsoft-r-open-mkl-3.3 needs to be reinstalled, but I can't find an archive for it.

### ISSUE THREAD

**Issue by jecogeo** [RevolutionAnalytics/RRO#313]
I downloaded and installed MRO as [documented](https://mran.microsoft.com/documents/rro/installation/), using ./install.sh. 
However a persistent error occurrs in mkl installation. I also tried to install the mkl itself by gdebi, but with no success.

I'll provide my terminal outputs and logs below:

**Terminal**

$ sudo ./install.sh 
[sudo] password for jeco: 

Press [Enter] key to display the Microsoft R Open license. When finished reading, press q to continue: 

Do you wish to install the Intel MKL libraries?
Choose [y]es|[n]o y

Press [Enter] key to display the Intel MKL license. When finished reading, press q to continue: 
Do you agree to the terms of the previously displayed license?
Choose [y]es|[n]o y

Updating apt package repositories...done
Installing apt package dependencies libxt6 libsm6 libpango1.0-0 libgomp1 curl...done
Installing /home/jeco/Downloads/microsoft-r-open/deb/microsoft-r-open-mro-3.3.deb...done
Installing /home/jeco/Downloads/microsoft-r-open/deb/microsoft-r-open-foreachiterators-3.3.deb...done
Installing /home/jeco/Downloads/microsoft-r-open/deb/microsoft-r-open-mkl-3.3.deb...ERROR!

There was an error installing Microsoft R Open.
Please check the logs at:
## /home/jeco/Downloads/microsoft-r-open/logs

**logs/dependencies.txt**

Reading package lists...
Building dependency tree...
Reading state information...
E: The package microsoft-r-open-mkl-3.3 needs to be reinstalled, but I can't find an archive for it.

---

**logs/foreachiterators.txt**

(Reading database ... 318542 files and directories currently installed.)
Preparing to unpack .../microsoft-r-open-foreachiterators-3.3.deb ...
Unpacking microsoft-r-open-foreachiterators-3.3 (3.3.1) over (3.3.1) ...
Setting up microsoft-r-open-foreachiterators-3.3 (3.3.1) ...

---

**logs/mkl.txt**

(Reading database ... 318542 files and directories currently installed.)
Preparing to unpack .../microsoft-r-open-mkl-3.3.deb ...
mv: cannot stat '/usr/lib64/microsoft-r/3.3/lib64/R/backup/lib/_.so': No such file or directory
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
rm: cannot remove '/usr/lib64/microsoft-r/3.3/lib64/R/lib/_.so': No such file or directory
mv: cannot stat '/usr/lib64/microsoft-r/3.3/lib64/R/backup/lib/_.so': No such file or directory
dpkg: error processing archive /home/jeco/Downloads/microsoft-r-open/deb/microsoft-r-open-mkl-3.3.deb (--install):
 subprocess new pre-removal script returned error exit status 1
mv: cannot stat '/usr/lib64/microsoft-r/3.3/lib64/R/lib/_.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.3/lib64/R/backup/lib/libR.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.3/stage/mkl_install_stage/*.so': No such file or directory
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 /home/jeco/Downloads/microsoft-r-open/deb/microsoft-r-open-mkl-3.3.deb

---

**logs/mro.txt**

(Reading database ... 318542 files and directories currently installed.)
Preparing to unpack .../microsoft-r-open-mro-3.3.deb ...
Unpacking microsoft-r-open-mro-3.3 (3.3.1) over (3.3.1) ...
Setting up microsoft-r-open-mro-3.3 (3.3.1) ...

---

**Comment by jecogeo** [comment]
For information: I'm doing it on Ubuntu 16.04.

**Comment by nathansoz** [comment]
Hi @jecogeo! We actually migrated this repository over to https://github.com/Microsoft/microsoft-r-open with this release. Would you mind opening this issue over there so that we can track it in MRO's new home?

**Comment by jecogeo** [comment]
Hi @nathansoz. Thanks for your reply. This issue was resolved right now in [MSDN](https://social.msdn.microsoft.com/Forums/en-US/a221ac44-22b7-462f-9a6a-2a40d4c80a16/error-microsoftropenmkl33-needs-to-be-reinstalled-but-i-can39t-find-an-archive-for-it?forum=ropen#c83b3d9c-537f-4282-a3fb-bc3d4cd407d6). But I'll remember MRO's new home in the future. Best regards.
