### ISSUE TITLE
Chocolatey / OneGet installation

### ISSUE THREAD

**Issue by nzbart** [RevolutionAnalytics/RRO#314]
Windows now has some nice command-line installation tools available, including Chocolatey (and hopefully OneGet soon). It would be nice to be able to install Microsoft R in our automated install scripts rather than CRAN R.

For reference, the Chocolatey package for CRAN R is here:
    [The R Project for Statistical Computing](https://chocolatey.org/packages/R.Project)

**Comment by nathansoz** [comment]
Migrated to issue: https://github.com/Microsoft/microsoft-r-open/issues/5
