### ISSUE TITLE
Disable automatic loading and saving of workspace

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#33]
In the interests of reproducibility, make RRO neither load nor save the workspace by default.

In standard R, this is achieved with

```
R --no-save --no-restore
```

In RRO, for the user to re-enable this functionality, they would need to launch RRO as follows

```
R --save --restore
```

**Comment by j-martens** [comment]
Assign to Josee when done Nick. 

(Josee: Add an FAQ on how to turn it back on)

**Comment by j-martens** [comment]
@nriesland are you ready for me to document now?

**Comment by nriesland** [comment]
yes, this is now part of the builds
