### ISSUE TITLE
Add startup message that indicates current MRAN snapshot

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/RRO#49]
Original suggestion by David Russell:

> I do wonder if it would be appropriate and beneficial to have your
simple function notify users when an implicit snapshot date is in use
(for example, a simple log statement in the R console: Using MRAN
snapshot: 2014-10-1). It might help demystify some of the magic by
making package dependencies explicit / discoverable on the otherwise
implicit `setSnapshot()` function call.

**Comment by sfweller** [comment]
Verified fix has been added to 8.0.3 on all supported platforms.
