### ISSUE TITLE
Doc Note:  RRO Installer doesn't work if booting OS from a Live-CD

### ISSUE THREAD

**Issue by sfweller** [RevolutionAnalytics/RRO#54]
Just a doc note for RRO users: I did some initial testing of the 8.0 installer on Ubuntu 12.04 after booting the OS from a Live-CD.  The installation script, 'install.sh' proceeded to run like everything was fine after I typed `sudo ./install.sh`
It finished, yet RRO was not unexpectedly non-functional after the script finished.

Everything works, if you install the Ubuntu OS to an actual file system partition.
I think we should mention this in the 'Requirements' section of the Installation Notes, as I think we might have some users, for reason or another, that try to boot from a Live-CD instead of doing a full install.

**Comment by j-martens** [comment]
@sfweller are you recommending that we say that installs of RRO on Ubuntu 12.04 from a live CD are not supported?  If so, is it only for 12.04 or also for 14.04, and 15.04? Thanks.

**Comment by sfweller** [comment]
Check with @revodavid, but I think for now our stance is that live CD installs will not be supported, regardless of the version of Ubuntu the customer is running. So we can probably close this issue.

**Comment by revodavid** [comment]
Fine with me, document as unsupported.

**Comment by sfweller** [comment]
Won't fix. Problem has been documented.
