### ISSUE TITLE
create dir for install.sh and .deb / .rpm files to live in as part of build process

### ISSUE THREAD

**Issue by cmosetick** [RevolutionAnalytics/RRO#86]
Right now `install.sh` and the `.deb` / `.rpm` files live next to where the user downloaded the `.tar.gz` file.

Creating a new directory for them to live in will make installation process much cleaner when someone downloads our installer .tar.gz files to some place like `~/Downloads` where there is potentially a lot of existing files already in the dir.

This should be a really low impact, but really beneficial change to the installers on Linux platforms.

**Comment by revodavid** [comment]
In general, tar files we distribute should always extract to a folder, rather than dumping files into cwd

**Comment by j-martens** [comment]
Assign to Josée when you've made the change on your end.

**Comment by j-martens** [comment]
Create new directory called:
/RRO_8.0.3

**Comment by nriesland** [comment]
completed for all Linux platforms.   directory is /RRO-8.0.3

**Comment by sfweller** [comment]
Verified that this issue has been fixed on all Linux platforms in RRO-8.0.3.
