### ISSUE TITLE
RRO install on Ubuntu creates /usr/lib64 directory

### ISSUE THREAD

**Issue by cmosetick** [RevolutionAnalytics/RRO#95]
### Overview
`/usr/lib64` directory does not exist natively on newer x64 Ubuntu installs. Since everything is [MultiArch](https://help.ubuntu.com/community/MultiArch) since Ubuntu 12.04, everything lives in `/usr/lib`. The RRO installer has sudo or root permissions, so it will create anything, even something that does not already exist.

### Detail
RRO installer creates a previously non-existing `/usr/lib64` directory, and thus the only thing that lives in this dir is the RRO installation.

```
ls /usr/lib64
RRO-8.0  RRO-8.0.1
```
__Though the installation works correctly, it seems less than ideal to create a directory that is out of practice with the current distribution standards.__

From the docs:
_Multiarch seeks to address all of these issues, at the expense of a one-time transition, by migrating libraries to subdirectories that include the architecture triplet as part of the path:_
```
   /lib/i386-linux-gnu
   /lib/x86_64-linux-gnu
   /usr/lib/i386-linux-gnu
   /usr/lib/x86_64-linux-gnu
```
References:
https://help.ubuntu.com/community/MultiArch
https://wiki.ubuntu.com/MultiarchSpec

**Comment by revodavid** [comment]
We should follow the appropriate Ubuntu policy regarding installation location.

**Comment by revodavid** [comment]
This is not in violation of any Ubuntu policies or best practices, so we won't make this change.
