### ISSUE TITLE
R 3.1.2 lib paths differ between CentOS and Ubuntu

### ISSUE THREAD

**Issue by cmosetick** [RevolutionAnalytics/RRO#96]
I think this is low priority, but it is something I am curious about.

The path to the RRO installation on CentOS is:
/usr/lib64/RRO-8.0.1/R-3.1.2 **/lib64** /R 

On Ubuntu the path is:
/usr/lib64/RRO-8.0.1/R-3.1.2 **/lib** /R

Note that this may or may not be related to issue #95.

**Comment by revodavid** [comment]
@sfweller please confirm whether this issue still exists in 8.0.2beta1

**Comment by sfweller** [comment]
This does not appear to be fixed yet - this is still an issue in the RRO 8.0.2 Beta for Ubuntu 14.

**Comment by j-martens** [comment]
It was decided as a group that we will not fix this behavior.
